[package]
name = "rc5_test"
version = "0.1.0"
authors = ["Ben Marsh <ben.marsh@mintlayer.org>"]
edition = "2018"

[dependencies]
log = "0.4.17"
thiserror = "1.0.34"


[dev-dependencies]
anyhow = "1.0.64"
pretty_env_logger = "0.4.0"